version: '3.7'

networks:
    LEMP:
        driver: bridge

services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                GROUP_ID: ${GROUPD_ID:-0}
        container_name: php
        restart: 'unless-stopped'
        volumes:
            - './app:/var/www'
        networks:
            - LEMP

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        restart: 'unless-stopped'
        volumes:
            - './app:/var/www'
            - './docker/nginx/conf:/etc/nginx/conf.d'
            - './docker/nginx/snippets:/etc/nginx/snippets'
            - './docker/nginx/log:/var/log/nginx'
        depends_on:
            - php
            - mariadb
        networks:
            - LEMP

    mariadb:
        image: 'mariadb:10.4.10'
        container_name: mariadb
        ports:
            - 127.0.0.1:3306:3306
        restart: 'unless-stopped'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
            MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
            MYSQL_USER: ${MYSQL_USER:?err}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
        volumes:
            - './docker/mariadb:/var/lib/mysql'
        networks:
            - LEMP
