version: '3.7'

networks:
    LEMP:
        driver: bridge

services:
    php:
        build:
            context: ./app/php
            dockerfile: Dockerfile
            args:
                HOST_USER_ID: ${HOST_USER_ID:-0}
                HOST_GROUP_ID: ${HOST_GROUP_ID:-0}
        container_name: php
        restart: 'unless-stopped'
        volumes:
            - './www:/var/www'
        networks:
            - LEMP

    nginx:
        build:
            context: ./app/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        restart: 'unless-stopped'
        volumes:
            - './www:/var/www'
            - './app/nginx/conf:/etc/nginx/conf.d'
            - './app/nginx/snippets:/etc/nginx/snippets'
            - './app/nginx/log:/var/log/nginx'
        depends_on:
            - php
            - mariadb
        networks:
            - LEMP

    mariadb:
        image: 'mariadb:10.4.10'
        container_name: mariadb
        ports:
            - 127.0.0.1:3306:3306
        restart: 'unless-stopped'
        command: --max_allowed_packet=64M
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
            MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
            MYSQL_USER: ${MYSQL_USER:?err}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:?err}
        volumes:
            - './app/mariadb:/var/lib/mysql'
        networks:
            - LEMP

    postfix:
        image: 'boky/postfix'
        container_name: postfix
        restart: 'always'
        environment:
            HOSTNAME: ${POSTFIX_HOSTNAME:-postfix-docker}
            ALLOWED_SENDER_DOMAINS: ${POSTFIX_ALLOWED_SENDER_DOMAINS:-}
        volumes:
            - './app/postfix/keys:/etc/opendkim/keys'
        networks:
            - LEMP
